/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KonohaComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLKonohaComponentElement extends Components.KonohaComponent, HTMLStencilElement {
    }
    var HTMLKonohaComponentElement: {
        prototype: HTMLKonohaComponentElement;
        new (): HTMLKonohaComponentElement;
    };
    interface HTMLElementTagNameMap {
        "konoha-component": HTMLKonohaComponentElement;
    }
}
declare namespace LocalJSX {
    interface KonohaComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "konoha-component": KonohaComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "konoha-component": LocalJSX.KonohaComponent & JSXBase.HTMLAttributes<HTMLKonohaComponentElement>;
        }
    }
}
